name: Dummy Test

on:
  pull_request:

jobs:
  always-pass:
    name: always-pass
    runs-on: ubuntu-latest
    steps:
      - name: Pass
        run: echo "This job always passes"

  fail-one:
    name: fail-one
    runs-on: ubuntu-latest
    steps:
      - name: Fail
        run: |
          echo "First failing job"
          exit 1

  fail-two:
    name: fail-two
    runs-on: ubuntu-latest
    steps:
      - name: Fail
        run: |
          echo "Second failing job"
          exit 1
