name: Huggingface CPU Docker Publisher

on:
  push:
    branches: [master]
    tags: [v*]
  pull_request:

jobs:
  publish:
    uses: ./.github/workflows/docker-publish.yml
    with:
      image-name: huggingfaceserver
      context: python
      dockerfile: python/huggingface_server_cpu.Dockerfile
      platforms: linux/amd64
    secrets: inherit
