name: PaddleServer Docker Publisher

on:
  push:
    branches: [master]
    tags: [v*]
  pull_request:

jobs:
  publish:
    uses: ./.github/workflows/docker-publish.yml
    with:
      image-name: paddleserver
      context: python
      dockerfile: python/paddle.Dockerfile
    secrets: inherit
