name: PMMLServer Docker Publisher

on:
  push:
    branches: [master]
    tags: [v*]
  pull_request:

jobs:
  publish:
    uses: ./.github/workflows/docker-publish.yml
    with:
      image-name: pmmlserver
      context: python
      dockerfile: python/pmml.Dockerfile
    secrets: inherit
