name: Re-Run PR Workflows

on:
  issue_comment:
    types: [created]

jobs:
  rerun:
    name: rerun
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '/rerun-failed')
    runs-on: ubuntu-latest
    steps:
      - name: Debug
        run: echo "Workflow triggered!"
