name: Router Docker Publisher

on:
  push:
    branches: [master]
    tags: [v*]
  pull_request:

jobs:
  publish:
    uses: ./.github/workflows/docker-publish.yml
    with:
      image-name: router
      dockerfile: router.Dockerfile
      platforms: linux/amd64,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x
    secrets: inherit
