name: Storage Initializer Docker Publisher

on:
  push:
    branches: [master]
    tags: [v*]
  pull_request:

jobs:
  publish:
    uses: ./.github/workflows/docker-publish.yml
    with:
      image-name: storage-initializer
      context: python
      dockerfile: python/storage-initializer.Dockerfile
    secrets: inherit
