name: Tf2Openapi Docker Publisher

on:
  push:
    branches: [master]
    tags: [v*]
  pull_request:

jobs:
  publish:
    uses: ./.github/workflows/docker-publish.yml
    with:
      image-name: tf2openapi
      dockerfile: tools/tf2openapi/Dockerfile
      platforms: linux/amd64
    secrets: inherit
