name: Transformer Docker Publisher

on:
  push:
    branches: [master]
  pull_request:

jobs:
  publish-image-transformer:
    uses: ./.github/workflows/docker-publish.yml
    with:
      image-name: image-transformer
      context: python
      dockerfile: python/custom_transformer.Dockerfile
      platforms: linux/amd64
    secrets: inherit

  publish-transformer-grpc:
    uses: ./.github/workflows/docker-publish.yml
    with:
      image-name: custom-image-transformer-grpc
      context: python
      dockerfile: python/custom_transformer_grpc.Dockerfile
      platforms: linux/amd64
    secrets: inherit
